# All project-specific additions and overrides should be specified in this 
# file.

inherit_from:
  # Thoughtbot's style guide from: https://github.com/thoughtbot/guides
  - ".rubocop.tb.yml"
AllCops:
  DisplayCopNames: false
  StyleGuideCopsOnly: false
  TargetRubyVersion: 2.4
Rails:
  Enabled: true
